-- Database schema for Smart Police Assistance System
-- The canonical MySQL setup and seed script is:
--   backend-node/init.sql
--
-- Run it from the project root with:
--   mysql -u root -p < backend-node/init.sql
--
-- Main tables:
--   1. users
--   2. cities
--   3. police_stations
--   4. officers
--   5. complaints
--   6. complaint_status
--   7. emergency_contacts
--   8. crime_reports
--   9. alerts
--   10. news
--   11. community_events
--   12. feedback
--
-- Supporting tables:
--   roles
--   evidence_files
